version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04

    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - MSSQL_SA_PASSWORD=Kyam123Kyam123

    ports:
      - 1433:1433

    container_name: sql-server-preview-1.0
    hostname: sqlpreview
